packages:
  - "."

allowBuilds:
  "@parcel/watcher": false
  "@tailwindcss/oxide": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - "@iconify-json/lucide@1.2.138"
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver
  - vue-demi
  - better-sqlite3
