packages:
  - "."

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - "@iconify-json/lucide@1.2.138"
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver
  - vue-demi
  - better-sqlite3
